4.Create a function to sort 2d Array by a column.

In [2]:
import numpy as np

In [ ]:
def sort_col(x, col: int):
    return x[x[:, col].argsort()]

In [ ]:
arr = np.random.randint(0, 100, (3, 4))
print(arr)
print(sort_col(arr, 1))

[[29 45 90 78]
 [21  3 55 48]
 [54 38 66 59]]
[[21  3 55 48]
 [54 38 66 59]
 [29 45 90 78]]
