### UE233106

1.Create a function to check whether numpy array has Zero values or not.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0, 100, 1000)

In [4]:
def check_zeros(x) -> bool:
    for ele in x:
        if ele == 0:
            return True

    return False

In [5]:
print(check_zeros(arr))
print(arr.any(0))

True
True


2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [6]:
import numpy as np

In [7]:
marks = np.random.rand(100) * 100
print(marks[:10])

[67.71800352 31.74044278 25.53527582 16.47190502 57.08413114 47.66494702
 48.34662501 16.84889381 17.3783668  64.1432243 ]


In [8]:
passing_marks = 33
passing_args = np.where(marks > passing_marks)
print(f"Passing indexes = {passing_args}")
print(f"Mean = {marks[passing_args].mean()}")
print(f"Median = {np.median(marks[passing_args])}")

Passing indexes = (array([ 0,  4,  5,  6,  9, 10, 11, 12, 13, 17, 18, 21, 23, 24, 25, 26, 27,
       28, 29, 31, 32, 33, 34, 36, 38, 39, 42, 43, 44, 45, 46, 48, 49, 51,
       53, 54, 56, 57, 59, 60, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75,
       77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 92, 94]),)
Mean = 66.12314641420188
Median = 66.15329342040532


3.Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [9]:
import numpy as np

In [10]:
base = np.random.randint(-5200, -3700, 100)
date = np.datetime64("2018-02-01")
birthdays = date + base

In [11]:
print(birthdays.shape)
print(birthdays[:10])

(100,)
['2006-03-07' '2006-02-09' '2006-01-20' '2006-03-10' '2005-02-19'
 '2006-07-14' '2007-01-31' '2006-11-13' '2003-12-16' '2005-01-29']


In [12]:
years_old = (np.datetime64("2026-02-04") - birthdays) / 365
years_old = years_old.reshape((years_old.size, 1))

In [13]:
labels = np.array(["First", "Second", "Third", "Forth", "Fifth"])
labeled_rows = labels[np.array(years_old - 18, dtype=np.int32)]

In [ ]:
print(np.hstack((years_old.astype(np.int32), labeled_rows)))

[['20' 'Third']
 ['19' 'Second']
 ['22' 'Fifth']
 ['21' 'Forth']
 ['21' 'Forth']
 ['19' 'Second']
 ['19' 'Second']
 ['20' 'Third']
 ['18' 'First']
 ['21' 'Forth']
 ['20' 'Third']
 ['19' 'Second']
 ['21' 'Forth']
 ['19' 'Second']
 ['20' 'Third']
 ['19' 'Second']
 ['21' 'Forth']
 ['18' 'First']
 ['21' 'Forth']
 ['18' 'First']
 ['18' 'First']
 ['19' 'Second']
 ['20' 'Third']
 ['20' 'Third']
 ['21' 'Forth']
 ['21' 'Forth']
 ['21' 'Forth']
 ['22' 'Fifth']
 ['19' 'Second']
 ['21' 'Forth']
 ['20' 'Third']
 ['22' 'Fifth']
 ['21' 'Forth']
 ['19' 'Second']
 ['22' 'Fifth']
 ['21' 'Forth']
 ['21' 'Forth']
 ['22' 'Fifth']
 ['18' 'First']
 ['21' 'Forth']
 ['19' 'Second']
 ['19' 'Second']
 ['19' 'Second']
 ['20' 'Third']
 ['21' 'Forth']
 ['20' 'Third']
 ['21' 'Forth']
 ['19' 'Second']
 ['20' 'Third']
 ['19' 'Second']
 ['19' 'Second']
 ['19' 'Second']
 ['21' 'Forth']
 ['18' 'First']
 ['22' 'Fifth']
 ['21' 'Forth']
 ['19' 'Second']
 ['18' 'First']
 ['21' 'Forth']
 ['21' 'Forth']
 ['21' 'Forth']
 ['21' 

4.Create a function to sort 2d Array by a column.

In [14]:
import numpy as np

In [15]:
def sort_col(x, col: int):
    return x[x[:, col].argsort()]

In [16]:
arr = np.random.randint(0, 100, (3, 4))
print(arr)
print(sort_col(arr, 1))

[[15 65 59 12]
 [64 66 63 62]
 [76 33 63 75]]
[[76 33 63 75]
 [15 65 59 12]
 [64 66 63 62]]
