Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be\
array([[ 0.,  1.,  0.],\
        [ 0.,  0.,  1.],\
        [ 0.,  1.,  0.],\
        [ 0.,  1.,  0.],\
        [ 0.,  1.,  0.],\
        [ 1.,  0.,  0.]])

In [1]:
import numpy as np

In [24]:
one_hot_values = np.random.randint(1, 4, 10)
print(one_hot_values)

base = np.zeros((one_hot_values.size, one_hot_values.max()))
base[np.arange(one_hot_values.size), one_hot_values - 1] = 1
print(base)

[3 2 1 1 2 2 2 3 2 3]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
