3.Find Index of Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 3, 7, 1, 2, 6, 0, 1])
arr_diff = np.diff(arr)
local_max = np.where(arr_diff < 0)
print(arr)
print(arr_diff)
print(local_max)

[1 3 7 1 2 6 0 1]
[ 2  4 -6  1  4 -6  1]
(array([2, 5]),)
