4.From the given 1d array arr, generate a 2d matrix using strides,\
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]\
w and s will be provided by user\
Calculate the moving average.

In [1]:
import numpy as np

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_len = 4
stride = 2
stacked_windows = []
for i in range(0, arr.size, stride):
    arr_segment = arr[i : i + window_len]
    stacked_windows.append(np.pad(arr_segment, (0, window_len - arr_segment.size)))
stacked_windows = np.stack(stacked_windows)
print(stacked_windows)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]
 [14  0  0  0]]


In [ ]:
beta = 0.5
avgs = []
for window in stacked_windows:
    if len(avgs) > 1:
        avgs.append(beta * avgs[-1] + (1 - beta) * window.mean())
    else:
        avgs.append(window.mean())
avgs = np.array(avgs)
print(avgs)

[1.5     3.5     4.5     6.      7.75    9.625   9.6875  6.59375]
