### UE233106

Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be\
array([[ 0.,  1.,  0.],\
        [ 0.,  0.,  1.],\
        [ 0.,  1.,  0.],\
        [ 0.,  1.,  0.],\
        [ 0.,  1.,  0.],\
        [ 1.,  0.,  0.]])

In [1]:
import numpy as np

In [2]:
one_hot_values = np.random.randint(1, 4, 10)
print(one_hot_values)

base = np.zeros((one_hot_values.size, one_hot_values.max()))
base[np.arange(one_hot_values.size), one_hot_values - 1] = 1
print(base)

[1 3 3 2 1 2 3 2 2 2]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


2.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
arr = arr[~np.isnan(arr)]
print(arr)

[1. 2. 3. 5. 6. 7.]


3.Find Index of Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [5]:
import numpy as np

In [8]:
arr = np.array([1, 3, 7, 1, 2, 6, 0, 1])
arr_diff = np.diff(arr)
local_max = np.where(arr_diff < 0)
print(arr)
print(arr_diff)
print(local_max)

[1 3 7 1 2 6 0 1]
[ 2  4 -6  1  4 -6  1]
(array([2, 5]),)


4.From the given 1d array arr, generate a 2d matrix using strides,\
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]\
w and s will be provided by user\
Calculate the moving average.

In [9]:
import numpy as np

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_len = 4
stride = 2
stacked_windows = []
for i in range(0, arr.size, stride):
    arr_segment = arr[i : i + window_len]
    stacked_windows.append(np.pad(arr_segment, (0, window_len - arr_segment.size)))
stacked_windows = np.stack(stacked_windows)
print(stacked_windows)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]
 [14  0  0  0]]


In [12]:
beta = 0.5
avgs = []
for window in stacked_windows:
    if len(avgs) >= 1:
        avgs.append(beta * avgs[-1] + (1 - beta) * window.mean())
    else:
        avgs.append(window.mean())
avgs = np.array(avgs)
print(avgs)

[1.5      2.5      4.       5.75     7.625    9.5625   9.65625  6.578125]
